AllCops:
  NewCops: enable
  # Minimum supported Ruby version (development uses 4.0.1)
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  Exclude:
    - "tmp/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

# rubocop-multiline_rhs_on_new_line.rb uses a dash by convention for RuboCop extensions
Naming/FileName:
  Exclude:
    - "lib/rubocop-*.rb"

# RSpec describe blocks naturally grow large; Metrics cops don't apply to specs
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
